### ISSUE TITLE
Adding New Service

### ISSUE THREAD

**Issue by andrewBSTan** [cywolf/permitify-x#2]
Using the Provisional VON Network with VON-X, how can we add a new service?
I believe we will need to register a new DID on the VON Network which will also get recognised by TheOrgBook.

But I am still trying to figure out how to add-on the Permitify Instance.  Help or assistance much appreciated.

Thanks.

**Comment by andrewwhitehead** [comment]
Hiya,

This repo is out of date now, it's superceded by https://github.com/bcgov/permitify which includes several example agents.

The DID registration should be automatic if you're using von-network.
